POST http://localhost:8080/user/add
Content-Type: application/json

{

   "login": "andrei",
   "firstName": "Andrei",
   "lastName": "Kviatkouski",
   "birthDate": "04/01/1986",
   "password": "andrei",
   "email": "Andrei@tut.by",
   "telephone": "+375(29)111-11-11",
   "role": "USER"
}

###

GET http://localhost:8080/user/auth?login=andrei&password=andrei

###
POST http://localhost:8080/user/address

###